//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SagaEvent.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORDER
    {
        public int orderId { get; set; }
        public string orderStatus { get; set; }
        public string paymentStatus { get; set; }
        public int guestNumber { get; set; }
        public System.DateTime eventDate { get; set; }
        public int eventId { get; set; }
        public int foodId { get; set; }
        public int userId { get; set; }
        public string eventPlace { get; set; }
    
        public virtual EVENT EVENT { get; set; }
        public virtual FOOD FOOD { get; set; }
        public virtual USER USER { get; set; }
    }
}
